### ISSUE TITLE
plot_similarity_matrix function not exists

### ISSUE THREAD

**Issue by yy9568** [krntz/Cluster-based-Sample-Selection#1]
@krntz Thank you for your great work! `plot_similarity_matrix` function seems to be lost, could you please provide complete code?

**Comment by yy9568** [comment]
@krntz

**Comment by krntz** [comment]
Hi mate! Sorry, for not responding. That method wasn't supposed to be included, however, I've added it back in. A word of warning though, do not use it with large datasets as it can get a bit unwieldy.

**Comment by yy9568** [comment]
@krntz Thank you!
